default_platform(:ios)

project_name = ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER']
sc_discord = ENV['DC_SCRIPT_PATH']

platform :ios do
  before_all do
    keychain_password = '12345678'

    sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Keychain Oluşturuluyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")

    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
    sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Keychain Oluşturuldu.", "Trippy-Dev-ios", "0", "Keychain Oluşturuldu.", "0x00ff00")

    
    if ENV["BUILD_PODS"] == 'true'

      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Podlar kuruluyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")

      cocoapods(
        podfile: ENV["PODS_PATH"],
        use_bundle_exec: false
      )
      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Podlar kuruldu.", "Trippy-Dev-ios", "0", "Podlar kuruldu.", "0x00ff00")
    end
  end

  sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Build başlatılıyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")
  desc "Build"
  lane :build do
    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_KEY_ID'],
      issuer_id: ENV['APPLE_KEY_ISSUER_ID'],
      key_content: ENV['APPLE_KEY_CONTENT'],
      duration: 500,
      in_house: false # optional but may be required if using match/sigh
    )

    use_workspace = !ENV['WORKSPACE_PATH'].empty?
    match(type: ENV['MATCH_BUILD_TYPE'], api_key: api_key)

    if ENV['INCREMENT_BUILD_NUMBER'] == 'true'
      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Build numarası ayarlanıyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")

      increment_build_number(
        xcodeproj: ENV['PROJECT_PATH'],
        build_number: (latest_testflight_build_number(
          app_identifier: ENV["IOS_APP_ID"],
          api_key: api_key,
          team_name: ENV["TEAM_NAME"],
        ) + 1).to_s,
      )

      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Build numarası ayarlandı.", "Trippy-Dev-ios", "0", "Build numarası ayarlandı.", "0x00ff00")

    end

    sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Build oluşturuluyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")

    
    build_app(
      workspace: use_workspace ? ENV['WORKSPACE_PATH'] : nil,
      project: !use_workspace ? ENV['PROJECT_PATH'] : nil,
      configuration: ENV['CONFIGURATION'],
      scheme: ENV['SCHEME'],
      output_directory: File.dirname(ENV['OUTPUT_PATH']),
      output_name: File.basename(ENV['OUTPUT_PATH']),
      clean: true,
      export_method: ENV['EXPORT_METHOD'],
      export_team_id: ENV['TEAM_ID'],
      silent: true,
      export_options: ENV['IOS_APP_ID'] != nil ? {
        provisioningProfiles: {
          "#{ENV['IOS_APP_ID']}" => "match AppStore #{ENV['IOS_APP_ID']}",
        },
      } : nil
    )
    
    sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Build oluşturuldu.", "Trippy-Dev-ios", "0", "Build oluşturuldu.", "0x00ff00")


    if ENV["BROWSERSTACK_UPLOAD"] == 'true'

      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Browserstack'a yükleniyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")

      upload_to_browserstack_app_live(
        browserstack_username: ENV["BROWSERSTACK_USERNAME"],
        browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
        file_path: ENV["OUTPUT_PATH"]
      )
      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Browserstack'a yüklendi.", "Trippy-Dev-ios", "0", "Browserstack'a yüklendi.", "0x00ff00")

    end

    if ENV["TESTFLIGHT_UPLOAD"] == 'true'

      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Testflight'a yükleniyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")

      upload_to_testflight(
        ipa: File.join(File.dirname(ENV['OUTPUT_PATH']), File.basename(ENV['OUTPUT_PATH'])),
        api_key: api_key,
        app_identifier: ENV['IOS_APP_ID'],
        team_name: ENV['TEAM_NAME'],
        skip_waiting_for_build_processing: true,
        skip_submission: true,
      )
      sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Testflight'a yüklendi.", "Trippy-Dev-ios", "0", "Testflight'a yüklendi.", "0x00ff00")

    end

    sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Build aşamaları tamamlandı.", "Trippy-Dev-ios", "0", "Build aşamaları tamamlandı.", "0x00ff00")

  end

  after_all do
    sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Keychain siliniyor.", "Trippy-Dev-ios", "0", "0", "0xffff00")

    delete_keychain(
      name: "ios-build.keychain"
    )
    sh("bash", ENV['DC_SCRIPT_PATH'], ENV['GITHUB_REPOSITORY']+" ["+ENV['GITHUB_REF']+"] #"+ENV['GITHUB_RUN_NUMBER'], "Keychain silindi.", "Trippy-Dev-ios", "0", "Keychain silindi.", "0x00ff00")

  end
end


